welcome:
  message: Welcome to Spring Boot3
spring:
  datasource:
    url: jdbc:postgresql://{url}:5432/javawithlwl
    username: {username}
    password: {password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
   secret:
      key: super_secret